-- MySQL Script generated by MySQL Workbench
-- Fri Feb 23 17:46:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Settings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Settings` (
  `idSettings` INT NOT NULL,
  `tresholdShrink` INT(10) NULL,
  `mapViewEnabled` TINYINT(1) NOT NULL,
  `displayDropDistance` TINYINT(1) NOT NULL,
  `timerRiddle` INT(10) NOT NULL,
  `lives` INT(10) NULL,
  `enableNextBeaconVisibility` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idSettings`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Game` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Game` (
  `idGame` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `joinCode` VARCHAR(45) NOT NULL,
  `gmCode` VARCHAR(45) NOT NULL,
  `type` INT(10) NOT NULL,
  `isStarted` TINYINT(1) NOT NULL,
  `Settings_idSettings` INT NOT NULL,
  PRIMARY KEY (`idGame`),
  INDEX `fk_Game_Settings1_idx` (`Settings_idSettings` ASC),
  CONSTRAINT `fk_Game_Settings1`
    FOREIGN KEY (`Settings_idSettings`)
    REFERENCES `mydb`.`Settings` (`idSettings`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Email` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Email` (
  `email` VARCHAR(50) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Riddle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Riddle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Riddle` (
  `idRiddle` INT NOT NULL,
  `statement` VARCHAR(45) NOT NULL,
  `answer` VARCHAR(45) NOT NULL,
  `type` INT(10) NOT NULL,
  PRIMARY KEY (`idRiddle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Beacon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Beacon` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Beacon` (
  `idBeacon` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `latitude` DECIMAL(8,5) NOT NULL,
  `longitude` DECIMAL(8,5) NOT NULL,
  `iconUrl` VARCHAR(50) NOT NULL,
  `Riddle_idRiddle` INT NOT NULL,
  `qrCodeID` VARCHAR(64) NULL,
  PRIMARY KEY (`idBeacon`),
  INDEX `fk_Beacon_Riddle1_idx` (`Riddle_idRiddle` ASC),
  CONSTRAINT `fk_Beacon_Riddle1`
    FOREIGN KEY (`Riddle_idRiddle`)
    REFERENCES `mydb`.`Riddle` (`idRiddle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Team` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Team` (
  `idTeam` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `iconURL` VARCHAR(45) NOT NULL,
  `colorRGB` VARCHAR(45) NOT NULL,
  `Game_idGame` INT NOT NULL,
  `lives` INT(4) NULL,
  `score` INT(10) NOT NULL,
  PRIMARY KEY (`idTeam`),
  INDEX `fk_Team_Game1_idx` (`Game_idGame` ASC),
  CONSTRAINT `fk_Team_Game1`
    FOREIGN KEY (`Game_idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Trip` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Trip` (
  `idTrip` INT NOT NULL,
  `distance` DECIMAL(8,5) NOT NULL,
  `heightDifference` DECIMAL(8,5) NOT NULL,
  `Team_idTeam` INT NOT NULL,
  PRIMARY KEY (`idTrip`),
  INDEX `fk_Trip_Team1_idx` (`Team_idTeam` ASC),
  CONSTRAINT `fk_Trip_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Beacon_has_Trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Beacon_has_Trip` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Beacon_has_Trip` (
  `Beacon_idBeacon` INT NOT NULL,
  `Trip_idTrip` INT NOT NULL,
  `index` INT(10) NOT NULL,
  PRIMARY KEY (`Beacon_idBeacon`, `Trip_idTrip`),
  INDEX `fk_Beacon_has_Trip_Trip1_idx` (`Trip_idTrip` ASC),
  INDEX `fk_Beacon_has_Trip_Beacon1_idx` (`Beacon_idBeacon` ASC),
  CONSTRAINT `fk_Beacon_has_Trip_Beacon1`
    FOREIGN KEY (`Beacon_idBeacon`)
    REFERENCES `mydb`.`Beacon` (`idBeacon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Beacon_has_Trip_Trip1`
    FOREIGN KEY (`Trip_idTrip`)
    REFERENCES `mydb`.`Trip` (`idTrip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Player` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Player` (
  `idPlayer` INT NOT NULL,
  `pseudonyme` VARCHAR(45) NOT NULL,
  `Team_idTeam` INT NOT NULL,
  PRIMARY KEY (`idPlayer`),
  INDEX `fk_Player_Team1_idx` (`Team_idTeam` ASC),
  CONSTRAINT `fk_Player_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
